# Generated by Django 5.0.6 on 2024-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_alter_task_status_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Ingrese la descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada')], default='pending', help_text='Establezca el estado de la tarea', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Ingrese el título de la tarea', max_length=200),
        ),
    ]
